//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiArmonii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int idLocal { get; set; }
        public Nullable<int> idMusico { get; set; }
        public Nullable<bool> estado { get; set; }
        public int duracion { get; set; }
    }
}
