//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiArmonii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int id { get; set; }
        public string direccion { get; set; }
        public string tipo_local { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
        public Nullable<System.TimeSpan> horarioApertura { get; set; }
        public Nullable<System.TimeSpan> horarioCierre { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
